PG_WETI_RS.docx: add initial version of file
esoviscode/docs pull request #23
Opened 2023-01-22 22:19 UTC by Silentsky0

2023-01-23 19:10 UTC, Mixss requested changes
1. Zaktualizować spis treści
2. Dodać terminologię typu *discord, bot, lobby*
3. Punkt **2.3** błąd ortograficzny *addytywnie* -> *addytywne*
4. Punkt **2.5** *inicjalnie* zamieniłbym na *wstępnie*
5.

2023-01-24 11:30 UTC, Silentsky0 commented
1. done
2. done
3. addytywne jest błędem ortograficznym, chodzi o sprinty `realizujące funkcjonalności (jak?) addytywnie`
4. done

2023-01-24 12:08 UTC, Mixss approved these changes

2023-01-24 12:09 UTC, Mixss approved these changes

2023-01-24 12:17 UTC, merged